/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as PollsRouteImport } from './routes/polls'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CorruptionCasesRouteImport } from './routes/corruption-cases'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'
import { Route as PersonSlugRouteImport } from './routes/person.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsRoute = PollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CorruptionCasesRoute = CorruptionCasesRouteImport.update({
  id: '/corruption-cases',
  path: '/corruption-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonSlugRoute = PersonSlugRouteImport.update({
  id: '/person/$slug',
  path: '/person/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/corruption-cases': typeof CorruptionCasesRoute
  '/donate': typeof DonateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/polls': typeof PollsRoute
  '/profiles': typeof ProfilesRoute
  '/projects': typeof ProjectsRoute
  '/submit': typeof SubmitRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/person/$slug': typeof PersonSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/corruption-cases': typeof CorruptionCasesRoute
  '/donate': typeof DonateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/polls': typeof PollsRoute
  '/profiles': typeof ProfilesRoute
  '/projects': typeof ProjectsRoute
  '/submit': typeof SubmitRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/person/$slug': typeof PersonSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/corruption-cases': typeof CorruptionCasesRoute
  '/donate': typeof DonateRoute
  '/leaderboard': typeof LeaderboardRoute
  '/polls': typeof PollsRoute
  '/profiles': typeof ProfilesRoute
  '/projects': typeof ProjectsRoute
  '/submit': typeof SubmitRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/person/$slug': typeof PersonSlugRoute
  '/project/$slug': typeof ProjectSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/corruption-cases'
    | '/donate'
    | '/leaderboard'
    | '/polls'
    | '/profiles'
    | '/projects'
    | '/submit'
    | '/article/$slug'
    | '/person/$slug'
    | '/project/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/corruption-cases'
    | '/donate'
    | '/leaderboard'
    | '/polls'
    | '/profiles'
    | '/projects'
    | '/submit'
    | '/article/$slug'
    | '/person/$slug'
    | '/project/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/corruption-cases'
    | '/donate'
    | '/leaderboard'
    | '/polls'
    | '/profiles'
    | '/projects'
    | '/submit'
    | '/article/$slug'
    | '/person/$slug'
    | '/project/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CorruptionCasesRoute: typeof CorruptionCasesRoute
  DonateRoute: typeof DonateRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PollsRoute: typeof PollsRoute
  ProfilesRoute: typeof ProfilesRoute
  ProjectsRoute: typeof ProjectsRoute
  SubmitRoute: typeof SubmitRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  PersonSlugRoute: typeof PersonSlugRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls': {
      id: '/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof PollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corruption-cases': {
      id: '/corruption-cases'
      path: '/corruption-cases'
      fullPath: '/corruption-cases'
      preLoaderRoute: typeof CorruptionCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$slug': {
      id: '/person/$slug'
      path: '/person/$slug'
      fullPath: '/person/$slug'
      preLoaderRoute: typeof PersonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CorruptionCasesRoute: CorruptionCasesRoute,
  DonateRoute: DonateRoute,
  LeaderboardRoute: LeaderboardRoute,
  PollsRoute: PollsRoute,
  ProfilesRoute: ProfilesRoute,
  ProjectsRoute: ProjectsRoute,
  SubmitRoute: SubmitRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  PersonSlugRoute: PersonSlugRoute,
  ProjectSlugRoute: ProjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
